// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  blankslate.routers.Account = (function(_super) {

    __extends(Account, _super);

    function Account() {
      return Account.__super__.constructor.apply(this, arguments);
    }

    Account.prototype.routes = {
      'account': "account"
    };

    Account.prototype.account = function() {
      var view;
      view = new blankslate.forms.AccountForm({
        model: this.page
      });
      return $('.profile.edit').html(view.render());
    };

    return Account;

  })(Backbone.Router);

}).call(this);
