// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    blankslate.app.routers.Account = new blankslate.routers.Account();
    return Backbone.history.start();
  });

}).call(this);
