// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  blankslate.models.Account = (function(_super) {

    __extends(Account, _super);

    function Account() {
      return Account.__super__.constructor.apply(this, arguments);
    }

    Account.prototype.defaults = {
      id: ""
    };

    Account.prototype.url = function() {
      var id;
      id = this.get('id');
      return "/api/1.0/account/?format=json";
    };

    return Account;

  })(Backbone.Model);

}).call(this);
