// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  blankslate.forms.AccountForm = (function(_super) {

    __extends(AccountForm, _super);

    function AccountForm() {
      return AccountForm.__super__.constructor.apply(this, arguments);
    }

    AccountForm.prototype.id = 'account-form';

    AccountForm.prototype.model = blankslate.models.Account;

    AccountForm.prototype.placeholder = '.form-horizontal';

    AccountForm.prototype.template = _.template($('#account-template').html());

    AccountForm.prototype.events = {
      '.btn-primary': 'save'
    };

    AccountForm.prototype.fields = {
      firstName: new Backbone.Fields.CharField({
        attr: 'first_name',
        label: 'First name',
        maxLength: 255
      }),
      middleName: new Backbone.Fields.CharField({
        attr: 'middle_name',
        label: 'Middle name',
        maxLength: 255
      }),
      lastName: new Backbone.Fields.CharField({
        attr: 'last_name',
        label: 'Last name',
        maxLength: 255
      }),
      email: new Backbone.Fields.EmailField({
        attr: 'email',
        label: 'Email'
      })
    };

    return AccountForm;

  })(Backbone.Form);

}).call(this);
